### ISSUE TITLE
How can I run a server?

### ISSUE THREAD

**Issue by oyenmwen** [Primitheus/Gemnet#1]
How can I run this locally and try it out as well? I think what you have here is great and promising. Would love to try it out and run my own server and possibly contribute in the future if possible

**Comment by Primitheus** [comment]
The entire source code needed to run the server is present. However to actually connect to it, you would need to reroute the connection to localhost, disable packet encryption within the client, and populate the SQL database with info needed to not crash the server, and of course, build the project. The hardest part of the process would be disabling encryption. Unfortunately I cannot help you with that.

**Comment by oyenmwen** [comment]
Apart from encryption disablement, can you give more details/step by step as to how to achieve the other steps?
- How can i reroute the connection to localhost? 
- What info is needed to not crash the server, is it just an account entry?
- How can I build the project

Thanks!

**Comment by Primitheus** [comment]
Firstly I apologize with the some-what complex setup, this is meant to be all automated in the future. 

- You can reroute the connection using windows "hosts" file or by using launch option /Server:127.0.0.1
- You first need to create the Schema "rumblefighter" then run the Server once for all the tables to populate. Then insert data such as account data and Important inventory items by ID like Class, Fishing Rod, and various default items. Avatar list and the Server ID of the item they have equipped.
- You need .NET to build the project. I believe .NET 7.0 would work, however I am using .NET 8.0. You can build by going to ".../Gemnet/Gemnet/" and executing "dotnet run" in Command Prompt. Or alternatively you can use Visual Studio to open the project. 

To run the Server you need a settings.json file

`{
  "ipAddress": "127.0.0.1",
  "Port": 7000,
  "P2PPort": 33343,
  "DBConnectionString": "Server=127.0.0.1;User=foo;Password=bar;Database=rumblefighter;"
}`

replacing your MySQL username and password in the DBConnectionString field.

Without disabling the encryption (which is actually quite difficult if you're not experienced) you won't be able to connect to the server. Furthermore without the Item IDs which are integers, you'll struggle to populate the database. There is some public information out there about Item IDs but it's limited. 

If you're still interested in helping or testing it out yourself I can give a few more pointers if you contact me by: 

(preferred) Discord: primitheus 
or
Email: primitheus@gmail.com

**Comment by oyenmwen** [comment]
Thank you so much for your help, will try all this out
